### ISSUE TITLE
utils.js

### ISSUE THREAD

**Issue by MaximePawlakFr** [Floune/Projet-Herrero-electron#2]
Que ce soit sur ce fichier ou les autres, ne soyez pas avares en commentaire pour expliquer brièvement ce que fait la fonction, ses paramètres et ce qu'elle retourne.

Autre point : 
console.log('generation 80');

Vraiment ?

**Comment by Floune** [comment]
J'ai commenté le plus de code que je pouvais et j'ai enlevé le console.log
